name: Hardhat Session
author: 721 Labs
description: "Run your Hardhat tests in a dedicated, session-lived container"
inputs:
  cmd:
    required: true
    description: "Hardhat cmd with args e.g. `npx hardhat <cmd>`"
  session-id:
    required: false
    description: "ID of session to resume; passed in from previous job"
  working-directory:
    required: false
    description: "Directory containing your Hardhat project, if not root."
    default: "."
outputs:
  _session-id:
    description: "Newly started session ID"
    value: ${{ steps.start-session.outputs.session-id }}
runs:
  using: "composite"
  steps:
    # - name: "Pre"
    #   run: "node dist/pre/index.js"
    #   shell: "bash"
    #   working-directory: ${{ inputs.working-directory }}
    #   env:
    #     INPUT_CMD: ${{ inputs.cmd }}
    - name: "DEV: Print Resumed Session ID"
      run: echo ${{ inputs.sessionId }}
      shell: "bash"
      if: ${{ inputs.sessionId }}
    - name: "Start Session"
      id: start-session
      run: "node dist/main/index.js"
      shell: "bash"
      if: ${{ inputs.sessionId == null }}
      # env:
      #   INPUT_CMD: ${{ inputs.cmd }}
      #   INPUT_FRESH: ${{ inputs.fresh }}
branding:
  color: "red"
  icon: "box"
