name: Hardhat Session
author: 721 Labs
description: "Run your Hardhat tests in a dedicated, session-lived container"
inputs:
  cmd:
    required: true
    description: "Hardhat cmd with args e.g. `npx hardhat <cmd>`"
  session-id:
    required: false
    description: "ID of session to resume; passed in from previous job"
  hardhat-directory:
    required: false
    description: "Directory containing your Hardhat project, if not root."
    default: "."
outputs:
  session-id:
    description: "Newly started session ID"
    value: ${{ steps.start-session.outputs.session-id }}
runs:
  using: "composite"
  steps:
    - name: "Copy pre into hardhat-dir"
      run: cp dist/pre/index.js ${{ inputs.hardhat-directory }}/pre.js
      shell: "bash"

    - name: "Validate Command"
      run: "node pre.js"
      shell: "bash"
      working-directory: ${{ inputs.hardhat-directory }}
      env:
        INPUT_CMD: ${{ inputs.cmd }}

    - name: "Resuming Session"
      run: |
        echo "Session Resumed: ${{ inputs.session-id }}"
      shell: "bash"
      if: ${{ inputs.session-id }}

    - name: "Start Session"
      id: start-session
      run: "node dist/main/index.js"
      shell: "bash"
      if: ${{ inputs.session-id == null }}
      # env:
      #   INPUT_CMD: ${{ inputs.cmd }}
      #   INPUT_FRESH: ${{ inputs.fresh }}
branding:
  color: "red"
  icon: "box"
