name: "CI"
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: "Install Dependencies"
        run: "yarn install"
      - name: "Build"
        run: "yarn build"
      - name: "Test"
        run: "yarn test"
  test-action:
    name: "Test Action"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: "Install Dependencies"
        run: "yarn install"
      - name: "Build"
        run: "yarn build"
      - name: "Cmd will fail"
        uses: ./
        with:
          cmd: dog
          fresh: true
      # - name: "Run against new session"
      #   uses: ./
      #   with:
      #     cmd: check --config ./tests/hardhat/hardhat.config.js # doesn't do anything other than validates that Hardhat is installed
      #     fresh: true
      # - name: "Run against resumed session"
      #   uses: ./
      #   with:
      #     cmd: check --config ./tests/hardhat/hardhat.config.js # doesn't do anything other than validates that Hardhat is installed
