name: "Release"
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "dist/**" # Don't recursively invoke.
      - ".github/workflows/release.yml"
  workflow_dispatch:
jobs:
  build-and-pr:
    name: "Build and PR"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: "yarn install"
      - name: Build
        run: "yarn build"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: "dist/"
          committer: "GitHub Action <action@github.com>"
          author: "GitHub Action <action@github.com>"
          signoff: "GitHub Action <action@github.com>"
          commit-message: "Release: v<version_tag>"
          title: "Release: v<version_tag>"
          body: ""
          base: "main"
          delete-branch: true
